# [editor_open]
# command = "nvim"

[preview]
syntax_highlighting = true
# syntax_highlighting_theme = "Catppuccin Macchiato"
# syntax_highlighting_theme = "Catppuccin Mocha"
# syntax_highlighting_theme = "Catppuccin Frappe"
syntax_highlighting_theme = "Catppuccin Macchiato"
